[workspace]
members = [
    "shapa",
]
resolver = "2"
exclude = [
    ".github",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"  # Optimize for size.
panic = "abort"
strip = true  # Automatically strip symbols from the binary.
