[package]
name = "toi_client"
version = "0.1.0"
edition = "2024"
description = "A client for self-hosting private assistants"
repository = "https://github.com/theOGognf/toi"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
ratatui = "0.29.0"
reqwest = "0.12.12"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.43.0"
