[package]
name = "toi_server"
version = "0.1.0"
edition = "2024"
description = "A server for self-hosting private assistants"
repository = "https://github.com/theOGognf/toi"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
axum = { version = "0.8.1", features = ["macros"] }
bb8 = "0.8"
chrono = { version = "0.4.40", features = ["serde"] }
diesel = { version = "2.2.8", features = ["chrono", "postgres"] }
diesel-async = { version = "0.5.2", features = ["bb8", "postgres"] }
dotenvy = "0.15.7"
pgvector = { version = "0.4.0", features = ["diesel", "serde"] }
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
utoipa = { version = "5.3.1", features = ["chrono"] }
utoipa-axum = "0.2.0"
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }
